#!/bin/bash
#
# pve: commandline Proxmox Virtual Environment interface
#

CFG=~/.pve-find.ini
SW="jq curl socat xtigervncviewer awk"
CACHE=~/.pve-cache

lib=$(realpath "$0")
lib="$( dirname "$lib" )/libpve.sh"
# shellcheck source=libpve.sh
if test -e "$lib"; then source "$lib"; else echo "Library not found."; exit 1; fi

declare -A COOKIE
declare -A TOKEN
TIMEOUT=1
# Login session time cache
SESSION=300

# pve_apireq <cluster> "extra args"
OLDpve_apireq() {
   local CMD; local data; local cookie; local token; local cache; local age
   local age
   local now; local cluster; local ret
   #CMD="curl -m $TIMEOUT --fail --silent --insecure --dump-header /dev/null"
   CMD="curl --fail --show-error --insecure --dump-header /dev/null"
   test "$verbose" -le 0 && CMD="$CMD --silent"

   local cluster="$1"
   shift

   test -e "$CACHE" && { chmod 600 "$CACHE"; cache="$(grep -m 1 ^$cluster$'\t' $CACHE)"; }
   if test "$cache" != ""; then
      message 2 "$cluster: Login cookie in cache."
      now=$(date "+%s")
      age=$(echo "$cache" | cut -d$'\t' -f 2)
      #message 1 "$cluster: ${now}_ _${age}_"
      if test "$(( now - age ))" -lt "$SESSION"; then
         message 2 "$cluster: Already logged in."
         token="$(echo "$cache" | cut -d$'\t' -f 3)"
         cookie="$(echo "$cache" | cut -d$'\t' -f 4- )"
      else
         flock -x -w 2 "$CACHE" sed -i "/^$cluster\t/d" "$CACHE"
         message 1 "$cluster: Cache invalid."
      fi
   fi

   if test "$cookie" = ""; then
      message 1 "$cluster: Logging in."
      data=$($CMD -d @<(cat <<<"username=${user[$cluster]}&password=${password[$cluster]}")  https://${hostname[$cluster]}:8006/api2/json/access/ticket 2> /dev/null)
      ret=$?
      test $ret -eq 7 && { message -1 "${hostname[$cluster]}: Failed to connect."; exit 1; }
      test $ret -eq 28 && { message -1 "${hostname[$cluster]}: Timed out."; exit 1; }
      test "$data" = "${data/ticket/}" && { message -1 "${hostname[$cluster]}: Unable to login."; exit 1; }
      cookie=$(echo $data | jq --raw-output '.data.ticket' | sed 's/^/PVEAuthCookie=/')
      token=$(echo $data | jq --raw-output '.data.CSRFPreventionToken')
      flock -x -w 2 "$CACHE" echo -e "$cluster\t$(date '+%s')\t$token\t$cookie" >> "$CACHE"
   fi
   $CMD --header "CSRFPreventionToken:$token" --cookie "$cookie" https://${hostname[$cluster]}:8006/api2/json/"$@"
   return $?
}

usage() {
   echo "Usage: pve <options> command"
   echo "Submits command tasks over multiple nodes/clusters on containers and VM's."
   echo
   echo "  -v      Be more verbose (increase every time option is used)."
   echo "  -q      Be quiet."
   echo "  -x      Debug mode enable."
   echo
   echo "  list <cluster>                            List vm's in all or specific cluster."
   echo "  status <vm name>|<vmid>@cluster           Shows status of vm."
   echo "  start <vm name>|<vmid>@cluster            Start vm."
   echo "  shutdown <vm name>|<vmid>@cluster         Shutdown vm."
   echo "  stop <vm name>|<vmid>@cluster             Force stop vm."
   echo "  stat <vm name>|<vmid>@cluster <interval>  Show vm statistics every interval times (defaults to 1)."
   echo "  createct <ct name>@cluster"
   echo "  destroy <vm name>|<vmid@cluster>          Destroy vm."
   echo "  snap <vm name>@cluster <snapshotname> [description]    Make snapshot."
   echo "  snaplist <vm name>@cluster                List snapshots."
   echo "  snaprm <vm name>@cluster <snapshotname>   Delete snapshot."
   echo "  snaprollback <vm name>@cluster                List snapshots."
   echo "  cfgshow <vm name>|<vmid>@cluster       Show vm configuration."
   echo "  cfgset <vm name>|<vmid>@cluster        Set vm configuration items."
   echo "  clone <vm name>|<vm name>@cluster         Clone vm."
  
   exit 1
}

action() {
   cluster=$1

   pve_apireq="curl  -f -s -k"

   test $verbose -eq 1 && echo "${hostname[$cluster]}: Connecting."
   data=$($pve_apireq -d @<(cat <<<"username=${user[$cluster]}&password=${password[$cluster]}")  https://${hostname[$cluster]}:8006/api2/json/access/ticket)
   ret=$?
   test $ret -eq 7 && { test $verbose -eq 1 && echo "${hostname[$cluster]}: Failed to connect."; exit 1; }
   test $ret -eq 28 && { test $verbose -eq 1 && echo "${hostname[$cluster]}: Timed out."; exit 1; }
   test "$data" = "${data/ticket/}" && { echo "${hostname[$cluster]}: Unable to login."; exit 1; }

   cookie=$(echo $data | jq --raw-output '.data.ticket' | sed 's/^/PVEAuthCookie=/')
   token="CSRFPreventionToken: $(echo $data | jq --raw-output '.data.CSRFPreventionToken')"

   pve_apireq="$pve_apireq -S -b $cookie"

   # port remains open for about 10 seconds
   curl -s --dump-header /dev/stderr -k -H "$token" -b "$cookie" -XPOST https://${hostname[$cluster]}:8006/api2/json/nodes/avon/qemu/200/vncproxy | jq .
   xtigervncviewer avon:5900
}

message() {
   local level=$1
   local msg="$2"
   local opt="$3"
   if test "$level" -lt 0 -a "$verbose" != "-1" ; then
      ( >&2 echo $opt "$msg" ) > /dev/null 
   else
      test "$verbose" -ge "$level" -a "$verbose" != "-1" && ( >&2 echo $opt "$msg" ) > /dev/null 
   fi
}

# find name in specific cluster
old_find_name() {
   local cluster=$1
   local name=$2
   local nodes; local node; local data; local result

   unset clause
   #test $active -eq 1 && clause="and .status == \"running\""

   nodes=$(pve_apireq $cluster nodes/ | jq -r ".data[] | .node")
   for node in $nodes; do
      data="$(pve_apireq $cluster nodes/$node/lxc/) $(pve_apireq $cluster nodes/$node/qemu/)"
      while read result; do 
         test "$result" != "" && echo "$cluster $result"
      done < <(echo $data | jq -r ".data[] | select((.name  | contains(\"$name\")) $clause) | \"$node \(.vmid) \(.name) \(.type // \"qemu\") \(.status)\"")
   done
}

old_sanity_check() {
   err=0

   ! test -f $CFG && { message - "No config file found ($CFG)."; err=1; }

   test $err -eq 0 && test $(stat -c %a $CFG) -gt 600 && { message -1 "Unsafe permissions on config file."; err=1; }

   for name in $SW
   do
      if ! which $name > /dev/null 2>&1
      then
         missing="$missing $name"
         err=1
      fi
   done
   test "$missing" != "" && message -1 "Missing required software to run script:$missing"

   test $# -lt 1 && { message -1 "At least one argument required."; err=1; }

   test $err -ne 0 && usage
}

parse_options() {
   while getopts :igcqvx opt; do
      case $opt in
         v) verbose=$(( verbose + 1 ))
         ;;
         q) verbose=-1
         ;;
         c) connect=1
         ;;
         g) graphical=1
         ;;
         i) active=0
         ;;
         x) set -x
         ;;
         \?) message -1 "Unknown options: -$OPTARG"
             usage
         ;;
      esac
   done
}

vnc() {
   server=$1
   type=$2
   vmid=$3
   message 1 "Connecting to server $server for $name..."

   port=$((netstat -atn | awk '{printf "%s\n%s\n", $4, $4}' | grep -oE '[0-9]*$'; seq 32768 61000) | sort -n | uniq -u | head -n 1)
   socat TCP-LISTEN:$port,bind=127.0.0.1 exec:"ssh root@$server qm vncproxy $vmid" &
   xtigervncviewer localhost:$port
}

clus_find_name() {
   local line
   local cluster
   local ret
   local vnname="$1"

   result=()
   # Check for id@cluster notation
   if test "${vmname/@/}" != "$vmname"; then
      cluster="${vmname/*@/}"
      id="${vmname/@*/}"
      nodes=$(pve_apireq $cluster nodes/ | jq -r ".data[] | .node")
      for node in $nodes; do
         data="$(pve_apireq $cluster nodes/$node/lxc/) $(pve_apireq $cluster nodes/$node/qemu/)"
         res=$(echo $data | jq -r ".data[] | select(.vmid==\"$id\") | \"$node \(.vmid) \(.name) \(.type // \"qemu\") \(.status)\"")
         test "$res" != "" && { res="$cluster $res"; result+=( "$res" ); }
      done
   else
      while read line; do
         if test "${line:0:1}" = "#"; then
            ret=( ${line:1} )
         else if test "$line" != ""; then
               result+=( "$line" )
            fi
         fi
      done < <( for cluster in ${!hostname[*]}; do
                   find_name $cluster $vmname & 
                   pids+=( $! )
                done 
                ret=0
                for pid in ${pids[*]}; do
                   wait $pid
                   ret=$(( ret + $? ))
                done
                echo "#$ret"
              )
      return $ret
   fi
}

vm_action() {
   local action="$1"
   local vmname="$2"
   local upid

   clus_find_name "$vmname"
   test "${#result[*]}" = 0 && { message -1 "No matches found."; exit 1; }
   test "${#result[*]}" -gt 1 && { message -1 "More than one match found."; vm_showmultiple; exit 1; }

   res=( ${result[0]} )
   upid=$(pve_apireq ${res[$R_CLUS]} nodes/${res[$R_HOST]}/${res[$R_TYPE]}/${res[$R_ID]}/status/$action -XPOST | jq -r .data)
   taskchk "${res[$R_CLUS]}" "${res[$R_HOST]}" "$upid"
   test "$?" -ne "0" && message -1 "Unable to $action ${res[$R_VM]}"
   return 0
}

# Try and see if we can open a websocket and use it as a terminal
#
# https://git.proxmox.com/?p=pve-xtermjs.git;a=blob;f=src/www/main.js;h=62ec1c1846dc2cccd39ae3cbe5f7345ac74e58ed;hb=refs/heads/master
# https://gist.github.com/htp/fbce19069187ec1cc486b594104f01d0
#
# socketURL = protocol + location.hostname + ((location.port) ? (':' + location.port) : '') + '/api2/json' + url + '/vncwebsocket?port=' + port + '&vncticket=' + encodeURIComponent(ticket);
#
vm_terminal() {
   local vmname="$1"

   clus_find_name "$vmname"
   test "${#result[*]}" = 0 && { message -1 "No matches found."; exit 1; }
   test "${#result[*]}" -gt 1 && { message -1 "More than one match found."; exit 1; }
   res=( ${result[0]} )
   data="$(pve_apireq ${res[$R_CLUS]} nodes/${res[$R_HOST]}/${res[$R_TYPE]}/${res[$R_ID]}/termproxy -XPOST)"
   port=$(echo $data | jq --raw-output .data.port)
   ticket=$(echo $data | jq --raw-output .data.ticket)

   cache=$(grep "^lnw " "$CACHE")
   token="$(echo $cache | cut -d ' ' -f 3)"
   cookie="$(echo $cache | cut -d ' ' -f 4-)"

   curl --get --include --no-buffer --insecure -H "Connection: Upgrade" \
      -H "Upgrade: websocket" -H "Sec-WebSocket-Version: 13" \
      -H "Sec-WebSocket-Protocol: base64" -H "Sec-WebSocket-Key: test" \
      --header "CSRFPreventionToken:$token" --cookie "$cookie" \
      "https://avon.lnw.verboom.net:8006/api2/json/nodes/${res[$R_HOST]}/${res[$R_TYPE]}/${res[$R_ID]}/vncwebsocket" \
      --data-urlencode "port=$port" \
      --data-urlencode "vncticket=$ticket"
}

vm_showmultiple() {
   test "$verbose" = "-1" && return
   for (( i = 0; i < ${#result[*]}; i++)); do
      res=( ${result[$i]} )
      echo "${res[$R_CLUS]}: ${res[$R_VM]} (${res[R_ID]})"
   done
}

vm_status() {
   local vmname="$1"

   clus_find_name "$vmname"
   test "${#result[*]}" = 0 && { message -1 "No matches found."; exit 1; }
   test "${#result[*]}" -gt 1 && { message -1 "More than one match found."; vm_showmultiple; exit 1; }
   res=( ${result[0]} )
   pve_apireq ${res[$R_CLUS]} nodes/${res[$R_HOST]}/${res[$R_TYPE]}/${res[$R_ID]}/status/current | jq  -r '.data | [.name, .status, .lock, .pid, .vmid, .cpus, .cpu, .disk, .maxdisk, .mem, .maxmem, .swap, .maxswap] | @tsv'
   test "$?" -ne "0" && message -1 "Unable to get status for $vmname"
}

vm_stat() {
   local vmname="$1"
   local int="$2"

   test "$int" = "" && int=5

   clus_find_name "$vmname"
   test "${#result[*]}" = 0 && { message -1 "No matches found for $vmname."; exit 1; }
   test "${#result[*]}" -gt 1 && { message -1 "More than one match found."; vm_showmultiple; exit 1; }
   res=( ${result[0]} )

   while test 1; do
      pve_apireq ${res[$R_CLUS]} nodes/${res[$R_HOST]}/${res[$R_TYPE]}/${res[$R_ID]}/status/current | jq -r ".data | [.cpu,.mem,.maxmem,.netin,.netout,.diskread,.diskwrite] | @tsv"
      sleep $int
   done | awk -vLINES=$LINES 'BEGIN { LINES--; line=LINES; 
             split("B KB MB GB TB PB EB ZB YB", B);
             split("b/s Kb/s Mb/s Gb/s Tb/s", bs);
             split("B/s KB/s MB/s GB/s TB/s", Bs);
             oldtime=systime()-1; netinold=0; netoutold=0; diskreadold=0; diskwriteold=0 }
             function ppB(num) {
                s=1
                while (num > 1024 && s < 9) {
                   num /= 1024
                   s++
                }
                return(sprintf("%6.1f%2s", num, B[s]));
             }
             function ppbs(num) {
                s=1;
                num=num*8;
                while (num > 1024 && s < 5) {
                   num /= 1024
                   s++
                }
                return(sprintf("%6.1f%4s", num, bs[s]));
             }
             function ppBs(num) {
                s=1;
                num=num;
                while (num > 1024 && s < 5) {
                   num /= 1024
                   s++
                }
                return(sprintf("%6.1f%4s", num, Bs[s]));
             }


             { if (line == LINES) {
                  printf("  cpu  -----memory------ -------network------- ---------disk--------\n");
                  printf("   %     alloc /  max         in       out          read    write\n");
                  line=2;
               }
             }
             { newtime=systime();
               cpu=$1*100; mem=$2; memmax=$3; netin=$4; netout=$5
               diskread=$6; diskwrite=$7
               if (netinold == 0) netinold=netin;
               if (netoutold == 0) netoutold=netout;
               if (diskreadold == 0) diskreadold=diskread;
               if (diskwriteold == 0) diskwriteold=diskwrite;
               netins=(netin - netinold)/(newtime-oldtime);
               netouts=(netout - netoutold)/(newtime-oldtime);
               diskreads=(diskread - diskreadold)/(newtime-oldtime);
               diskwrites=(diskwrite - diskwriteold)/(newtime-oldtime);
               printf("%5.1f%% %s/%s %s %s %s %s\n", cpu, ppB(mem), ppB(memmax), ppbs(netins), ppbs(netouts), ppBs(diskreads), ppBs(diskwrites));
               line++;
               oldtime=newtime;
               netinold=netin;
               netoutold=netout;
               diskreadold=diskread;
               diskwriteold=diskwrite;
             }'
}

# Create a container
#
# Requires:
# cluster
# network bridge + device name
# ostemplate
# vmid -> retrieve next from cluster properties
# make system in cluster optional, default to localhost
ct_create() {
   declare -A vars=(['unpriv']='1' 
                    ['boot']='0' 
                    ['tmpl']='' 
                    ['mem']='1024'
                    ['swap']='256'
                    ['rootfs']=''
                    ['rootsize']='4' )
   local extraargs=""
   local vmname="$1"
   shift

   if test "${vmname/@/}" != "$vmname"; then
      cluster="${vmname/*@/}"
      vmname="${vmname/@*/}"
   else
      usage
   fi
   # Check for defaults from configuration or assign default
   for var in ${!vars[@]}; do
      tmp="$var[$cluster]"
      test "${vars[$var]}" != "" && declare "$var=${vars[$var]}"
      test "${!tmp}" != "" && declare "$var=${!tmp}"
      case "$var" in
         "tmpl")
            tmp="${var}_${!tmp}[$cluster]"
            tmpl="${!tmp}"
         ;;
      esac
   done

   while test "$#" -ne "0"; do
      if test "$1" != "${1/=/}"; then label="${1/=*/}"; else label="$1"; fi
      case "$label" in
      "tmpl") tmpl="${1/*=/}"
              tmpl="tmpl_$tmpl[$cluster]"
              tmpl="${!tmpl}"
              test "$tmpl" = "" && tmpl="${1/*=/}"
      ;;
      "net") 
           #--data-urlencode net0="name=eth0,bridge=vmbr10,ip=192.168.1.245/24,gw=192.168.1.1"
           # net=eth0,vmbr10,192.168.1.245/24 n=eth1,vmbr10
      ;;
      *) if test "${vars[$label]+abc}"; then
            declare "$label=${1/*=/}"
         else
            message -1 "Unknown argument $label"
         fi
      ;;
      esac
      shift
   done
   # Check if all variable are defined
   err=0
   for var in ${!vars[@]}; do
      test "${!var}" = "" && { message 0 "Variable $var not defined."; err=1; }
   done
   test "$err" -gt "0" && exit 1

   ctid=$(pve_apireq $cluster cluster/nextid | jq --raw-output .data)
   test "$ctid" = "" && message -1 "Unable to get free id."
   upid=$(pve_apireq $cluster nodes/localhost/lxc -XPOST \
      --data-urlencode vmid=$ctid \
      --data-urlencode hostname=$vmname \
      --data-urlencode ostemplate="$tmpl" \
      --data-urlencode unprivileged="$unpriv" \
      --data-urlencode memory="$mem" \
      --data-urlencode swap="$swap" \
      --data-urlencode rootfs="$rootfs:$rootsize" \
      $extraargs | jq -r .data)
   taskchk "$cluster" "localhost" "$upid"
   test "$?" -ne "0" && { message -1 "Unable to create container"; return 1; }
   echo $ctid
   return 0
}

vm_cfgset() {
   local vmname="$1"
   local upid
   local opts
   local del

   declare -A allowed=( ['cores']='1'
                        ['cpulimit]='1'
                        ['cpuunits]='1'
                        ['description']='1'
                        ['lock']='1'
                        ['memory']='1'
                        ['nameserver']='1'
                        ['onboot']='1'
                        ['searchdom']='1'
                        ['startup']='1'
                        ['swap']='1'
                        ['tty']='1'
                        ['hostname']='1' )
   shift

   clus_find_name "$vmname"
   test "${#result[*]}" = 0 && { message -1 "No matches found."; exit 1; }
   test "${#result[*]}" -gt 1 && { message -1 "More than one match found."; vm_showmultiple; exit 1; }
   res=( ${result[0]} )

   while test "$#" -ne "0"; do
      if test "$1" != "${1/=/}"; then 
         label="${1/=*/}"
         val="${1/*=/}"
      else
         label="$1"
      fi
      test "${allowed[$label]}" != "1" && { message -1 "Option $label unknown."; exit 1;}
      if test "$1" != "${1/=/}"; then 
         opts+=( --data-urlencode $label="$val" )
      else
         del+=" $label"
      fi
      shift
   done
   if test "$del" != ""; then
      del="${del/ /}"
      del="${del// /,}"
      opts+=( --data-urlencode delete=$del )
   fi

   pve_apireq ${res[$R_CLUS]} \
      nodes/${res[$R_HOST]}/${res[$R_TYPE]}/${res[$R_ID]}/config \
      "${opts[@]}" \
      -XPUT > /dev/null
   test "$?" -ne "0" && { message -1 "Unable to change configuration for $vmname"; return 1; }
   return 0
}

vm_destroy() {
   local vmname="$1"
   local upid

   clus_find_name "$vmname"
   test "${#result[*]}" = 0 && { message -1 "No matches found."; exit 1; }
   test "${#result[*]}" -gt 1 && { message -1 "More than one match found."; vm_showmultiple; exit 1; }
   res=( ${result[0]} )
   upid=$(pve_apireq ${res[$R_CLUS]} nodes/${res[$R_HOST]}/${res[$R_TYPE]}/${res[$R_ID]} -XDELETE | jq -r .data)
   taskchk "${res[$R_CLUS]}" "${res[$R_HOST]}" "$upid"
   test "$?" -ne "0" && { message -1 "Unable to destroy $vmname"; return 1; }
   return 0
}

vm_snap() {
   local vmname="$1"
   local snapshot="$2"
   local desc="$3"
   local upid

   test "$snapshot" = "" && { message -1 "Requires snapshot name"; exit 1; }

   clus_find_name "$vmname"
   test "${#result[*]}" = 0 && { message -1 "No matches found."; exit 1; }
   test "${#result[*]}" -gt 1 && { message -1 "More than one match found."; vm_showmultiple; exit 1; }
   res=( ${result[0]} )
   upid=$(pve_apireq ${res[$R_CLUS]} \
      nodes/${res[$R_HOST]}/${res[$R_TYPE]}/${res[$R_ID]}/snapshot -XPOST \
      --data-urlencode snapname="$snapshot" \
      --data-urlencode description="$desc" | jq -r .data)
   taskchk "${res[$R_CLUS]}" "${res[$R_HOST]}" "$upid"
}

vm_snaplist() {
   local vmname="$1"

   clus_find_name "$vmname"
   test "${#result[*]}" = 0 && { message -1 "No matches found."; exit 1; }
   test "${#result[*]}" -gt 1 && { message -1 "More than one match found."; vm_showmultiple; exit 1; }
   res=( ${result[0]} )
   pve_apireq ${res[$R_CLUS]} \
      nodes/${res[$R_HOST]}/${res[$R_TYPE]}/${res[$R_ID]}/snapshot | jq -r '.data | sort_by(.snaptime)[] | select(.snaptime!=null) | [.name, .snaptime, .description] | @tsv' | awk -F $'\t' '{ printf("%s %s (%s)\n", strftime("%Y/%m/%d %H:%M:%S", $2), $1, $3); }'
   test "$?" -ne "0" && message -1 "Unable to list snapshots for $vmname"
}

vm_snaprm() {
   local vmname="$1"
   local snapshot="$2"
   local upid

   test "$snapshot" = "" && { message -1 "Requires snapshot name"; exit 1; }

   clus_find_name "$vmname"
   test "${#result[*]}" = 0 && { message -1 "No matches found."; exit 1; }
   test "${#result[*]}" -gt 1 && { message -1 "More than one match found."; vm_showmultiple; exit 1; }
   res=( ${result[0]} )
   pve_apireq ${res[$R_CLUS]} \
      nodes/${res[$R_HOST]}/${res[$R_TYPE]}/${res[$R_ID]}/snapshot/$snapshot/config > /dev/null
   test "$?" -ne "0" && { message -1 "Snapshot $snapshot doesn't exist on ${res[$R_VM]}."; exit 1; }
   upid=$(pve_apireq ${res[$R_CLUS]} \
      nodes/${res[$R_HOST]}/${res[$R_TYPE]}/${res[$R_ID]}/snapshot/$snapshot \
      -XDELETE  | jq -r .data)
   taskchk "${res[$R_CLUS]}" "${res[$R_HOST]}" "$upid"
   test "$?" -ne "0" && message -1 "Unable to delete snapshot $snapshot for $vmname"
}

vm_snaprollback() {
   local vmname="$1"
   local snapshot="$2"
   local upid

   test "$snapshot" = "" && { message -1 "Requires snapshot name"; exit 1; }

   clus_find_name "$vmname"
   test "${#result[*]}" = 0 && { message -1 "No matches found."; exit 1; }
   test "${#result[*]}" -gt 1 && { message -1 "More than one match found."; vm_showmultiple; exit 1; }
   res=( ${result[0]} )
   pve_apireq ${res[$R_CLUS]} \
      nodes/${res[$R_HOST]}/${res[$R_TYPE]}/${res[$R_ID]}/snapshot/$snapshot/config > /dev/null
   test "$?" -ne "0" && { message -1 "Snapshot $snapshot doesn't exist on ${res[$R_VM]}."; exit 1; }
   upid=$(pve_apireq ${res[$R_CLUS]} \
      nodes/${res[$R_HOST]}/${res[$R_TYPE]}/${res[$R_ID]}/snapshot/$snapshot/rollback \
      -XPOST  | jq -r .data)
   taskchk "${res[$R_CLUS]}" "${res[$R_HOST]}" "$upid"
   test "$?" -ne "0" && message -1 "Unable to rollback snapshot $snapshot for $vmname"
}

# ToDo: 
# * check if running
vm_clone() {
   local vmname="$1"
   local upid
   local cloneid

   clus_find_name "$vmname"
   test "${#result[*]}" = 0 && { message -1 "No matches found."; exit 1; }
   test "${#result[*]}" -gt 1 && { message -1 "More than one match found."; vm_showmultiple; exit 1; }
   res=( ${result[0]} )
   cloneid=$(pve_apireq ${res[$R_CLUS]} cluster/nextid | jq --raw-output .data)
   upid=$(pve_apireq ${res[$R_CLUS]} \
      nodes/${res[$R_HOST]}/${res[$R_TYPE]}/${res[$R_ID]}/clone \
      --data-urlencode newid="$cloneid" \
      -XPOST  | jq -r .data)
   taskchk "${res[$R_CLUS]}" "${res[$R_HOST]}" "$upid"
   if test "$?" -ne "0";then
      message -1 "Unable to clone $vmname"
      return 1
   else
      echo "$cloneid"
   fi
}

vm_cfgshow() {
   local vmname="$1"
   local upid

   clus_find_name "$vmname"
   test "${#result[*]}" = 0 && { message -1 "No matches found."; exit 1; }
   test "${#result[*]}" -gt 1 && { message -1 "More than one match found."; vm_showmultiple; exit 1; }
   res=( ${result[0]} )
   pve_apireq ${res[$R_CLUS]} \
      nodes/${res[$R_HOST]}/${res[$R_TYPE]}/${res[$R_ID]}/config | jq -r '.data'
}

taskchk() {
   local cluster="$1"
   local node="$2"
   local upid="$3"
   local status="running"
   local pos=0
   local anim='|/-\'

   test "$upid" = "" && { message -1 "No task running."; return 1 ; }
   #message 0 "run." -n

   while test "$status" = "running"; do
      eval $(pve_apireq "$cluster" nodes/$node/tasks/$upid/status | jq -r '"status=" + .data.status + "\nexitstatus=\"" + .data.exitstatus + "\""' )
      message 0 "${anim:$pos:1}" -n
      pos=$(( pos + 1 ))
      test $pos -ge ${#anim} && pos=0
      sleep 0.5
   done
   if test "$exitstatus" != "OK"; then
      message -1 "fail: $exitstatus"
      return 1
   else
      message 0 "ok"
      return 0
   fi
}

vm_list() {
   local nodes
   local clusnodes
   local cluster

   if test "$1" != ""; then
      clusnodes="$1"
   else
      clusnodes="${!hostname[*]}"
   fi

   for cluster in $clusnodes; do
      nodes=$(pve_apireq $cluster nodes/ | jq -r ".data[] | .node")
      for node in $nodes; do
         ( pve_apireq $cluster nodes/$node/lxc/; pve_apireq $cluster nodes/$node/qemu/ ) | jq -r ".data[] | \"$node \(.vmid) \(.name) \(.type // \"qemu\") \(.status)\""
      done
   done 
}

main() {
   unset https_proxy
   verbose=0
   graphical=0

   sanity_check "$@"
   pve_readconfig $CFG
   parse_options "$@"
   shift $((OPTIND -1))
   cmd="$1"
   name="$2"

   case "$cmd" in
      "start"|"shutdown"|"stop"|"suspend"|"resume")
         vm_action "$@"
      ;;
      "status")
         shift
         vm_status "$@"
      ;;
      "stat")
         shift
         vm_stat "$@"
      ;;
      "term")
         shift
         vm_terminal "$@"
      ;;
      "createct")
         shift
         ct_create "$@"
      ;;
      "destroy")
         shift
         vm_destroy "$@"
      ;;
      "snap")
         shift
         vm_snap "$@"
      ;;
      "snaplist")
         shift
         vm_snaplist "$@"
      ;;
      "snaprm")
         shift
         vm_snaprm "$@"
      ;;
      "snaprollback")
         shift
         vm_snaprollback "$@"
      ;;
      "clone")
         shift
         vm_clone "$@"
      ;;
      "cfgshow")
         shift
         vm_cfgshow "$@"
      ;;
      "cfgset")
         shift
         vm_cfgset "$@"
      ;;
      "list")
         shift
         vm_list "$@"
      ;;
      "list-clusters")
         printf "%s\n" "${!hostname[@]}"
      ;;
      *) usage
      ;;
   esac
}

main "$@"
