#!/bin/bash
#
# ToDo:
# * jq
# * .pve-find.ini

CFG=~/.pve-find.ini
SW="jq curl"

usage() {
   echo "Usage: pve-find [name]"
   echo "Searches all nodes/clusters defined in the config file for VM/CT names containing"
   echo "the given name."
   exit 1
}

parse_config() {

   while IFS='= ' read var val
   do
      if [[ $var == \[*] ]]
      then
          section=${var:1:-1}
      elif [[ $val ]]
      then
          declare -g -A "$var[$section]=$val"
      fi
   done < $CFG
}

find_name() {
   cluster=$1
   name=$2

   data=$(curl -s -k -d "username=${user[$cluster]}&password=${password[$cluster]}"  https://${hostname[$cluster]}:8006/api2/json/access/ticket)
   test "$data" = "${data/ticket/}" && { echo "Unable to login to PVE."; exit 1; }

   cookie=$(echo $data | jq --raw-output '.data.ticket' | sed 's/^/PVEAuthCookie=/')
   token=$(echo $data | jq --raw-output '.data.CSRFPreventionToken')
   CURL='curl -f -s -S -k -b $cookie -H "CSRFPreventionToken: '$token'" '
   CURL="curl -f -s -S -k -b $cookie"
   
   nodes="$($CURL -H "CSRFPreventionToken: $token" https://${hostname[$cluster]}:8006/api2/json/nodes/ | jq -r ".data[] | .node")"
   for node in $nodes
   do
      match=$($CURL -H "CSRFPreventionToken: $token" https://${hostname[$cluster]}:8006/api2/json/nodes/$node/lxc/ | jq -r ".data[] | .name" | grep -i $name)
      test "$match" != "" && { for zone in $match; do echo "$node: $zone (lxc)"; done; }
      match=$($CURL -H "CSRFPreventionToken: $token" https://${hostname[$cluster]}:8006/api2/json/nodes/$node/qemu/ | jq -r ".data[] | .name" | grep -i $name)
      test "$match" != "" && { for zone in $match; do echo "$node: $zone (qemu)"; done; }
   done
}

sanity_check() {
   err=0

   ! test -f $CFG && { echo "No config file found ($CFG)."; err=1; }

   for name in $SW
   do
      if ! which $name > /dev/null 2>&1
      then
         missing="$missing $name"
         err=1
      fi
   done
   test "$missing" != "" && echo "Missing required software to run script:$missing"

   test $# -ne 1 && { echo "One argument required."; err=1; }
   name=$1

   test $err -ne 0 && usage
}

main() {
   unset https_proxy

   sanity_check "$@"

   parse_config

   for cluster in ${!hostname[*]}
   do
      find_name $cluster $name
   done
}

main "$@"
